name: CICD

on:
  push:
    branches:
    - 'main'
    - 'alpha'
    - 'beta'
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  actions: write
  checks: write
  issues: write
  pull-requests: write

jobs:
  call-workflow:
    uses: IvanJosipovic/KubernetesCRDModelGen/.github/workflows/cicd-template.yaml@main
    secrets:
      GH_TOKEN: ${{ secrets.GHPAT }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}